name: ci-golang-workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Display Go version
        run: go version

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GOPATH }}/pkg/mod
          key: go-${{ hashFiles('**/*.go') }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run application
        run: go run math.go

      - name: Clear Go Modules Cache
        run: go clean -modcache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gustavon/ci-example:latest
